pipeline {
    agent any

    environment {
        S3_BUCKET = 'apps-project'
        S3_KEY = 'my-app.zip'
        ENVIRONMENT_NAME = 'Firstproject-env'
        APPLICATION_NAME = 'Firstproject'
        AWS_REGION = 'us-east-1'
        SECRET_NAME = 'jenkins-aws-creds'  // Replace with your actual secret name
        VERSION_LABEL = "app-version-${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/NagendraOruganti/-updated-jenkins.git', branch: 'main'
            }
        }
        
        stage('Upload to S3') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-configure']]) {
                    sh "aws s3 cp application.zip s3://${S3_BUCKET}/${S3_KEY} --region ${AWS_REGION}"
                }
            }
        }

        stage('Create Application Version') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-configure']]) {
                    sh """
                        aws elasticbeanstalk create-application-version \
                        --application-name ${APPLICATION_NAME} \
                        --version-label ${VERSION_LABEL} \
                        --source-bundle S3Bucket=${S3_BUCKET},S3Key=${S3_KEY} \
                        --region ${AWS_REGION}
                    """
                }
            }
        }

        stage('Update Elastic Beanstalk Environment') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-configure']]) {
                    sh """
                        aws elasticbeanstalk update-environment \
                          --application-name ${APPLICATION_NAME} \
                          --environment-name ${ENVIRONMENT_NAME} \
                          --version-label ${VERSION_LABEL} \
                          --region ${AWS_REGION}
                    """
                }
            }
        }
    }

    post {
        always {
            echo 'Deployment process completed.'
        }
    }
}
